### PR TITLE
Initial commit for Meetup API Wrapper

### PR DESCRIPTION
**Pull request by tjnoe**
Here's the initial commit for the Meetup API Wrapper.  I'd like to add some improvements in the near future, but this will work fine for now!

### CODE REVIEW

**Comment by dsberger** [comment]
This looks great Tommy. Have you considered using the [Revealing Module Pattern](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#revealingmodulepatternjavascript)? It's where the return object doesn't contain the public functions, it just contains key-value pairs that point to the public function inside the closure.

```
return {
  setKey: setKey,
  getOpenEvents: getOpenEvents
}
```

It makes the methods even more private because the _internals_ of your public method are not visible to the user.

**Comment by tjnoe** [comment]
Thanks Dan.  The Revealing Module Pattern looks great and is an easy change, so I switched to that pattern.  Also fixed the getParams function so that it doesn't add an unnecessary "&" at the beginning of the query string.

**Comment by dsberger** [comment]
Anyone else want to comment? I think this looks good to merge. Tommy you can do the honors.

**Comment by tjnoe** [comment]
Hey Dan, it says I need write access to merge the pull request.  Could you set me up with the correct permissions, or you could also merge as well, whichever works!

**Comment by dsberger** [comment]
hey Tommy, it seems that I sent you an invitation to join the JS-Enabled collaborators team, but you haven't accepted yet. I cancelled that invitation and sent another so you don't have to go looking in your mail archives.

**Comment by tjnoe** [comment]
Thanks Dan, got it now!  Merging!

**Pull request merged**
